install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages(c("boot","data.table","ggplot2","pdp","rpart"))
install.packages(c("broom","devtools","glmnet","pls","rpart.plot"))
install.packages(c("caret","dplyr","gridExtra","plyr","tidyverse"))
install.packages(c("cluster","e1071","ISLR","pROC","xgboost"))
install.packages(c("coefplot","gbm","MASS","randomForest"))

